### ISSUE TITLE
[FAQ] How this project different from https://github.com/rossta/serviceworker-rails ?

### ISSUE THREAD

**Issue by kirantpatil** [jonhue/pwa#21]
Hi,

I would like to know which one to use for PWA in rails.

I could see other project as well which is https://github.com/rossta/serviceworker-rails.

Thanks.

**Comment by jonhue** [comment]
ServiceWorker::Rails offers more customization while this project is easier to setup.

**Comment by kirantpatil** [comment]
Thanks a lot @jonhue.

I have two more questions below.

Is it production ready ?

Is this project done or are you implementing additional features on top it ?

**Comment by jonhue** [comment]
It is production ready. There are no features planned. But I would love to hear some ideas & review pull requests.
