### ISSUE TITLE
[FAQ] Installation steps 

### ISSUE THREAD

**Issue by kirantpatil** [jonhue/pwa#22]
Hi,

I am following your installation steps and some of them are confusing as below.

In which file to add these lines ?

```
Pwa.configure do |config|
    config.define_app 'App'
end
```
```
import ProgressiveWebApp from 'pwa-rails';
document.addEventListener( 'turbolinks:load', () => {
    const progressiveWebApp = new ProgressiveWebApp();
})
```
```
Pwa.configure do |config|
    config.define_app 'Subdomain', ['subdomain.example.com', 'subdomain.lvh.me:3000']
    config.define_app 'Example', ['example.com', 'localhost:3000', 'lvh.me:3000']
end
```

Instead, If you have a sample app, please upload it.

Thanks.

**Comment by jonhue** [comment]
```ruby
Pwa.configure do |config|
    config.define_app 'App'
end

Pwa.configure do |config|
    config.define_app 'Subdomain', ['subdomain.example.com', 'subdomain.lvh.me:3000']
    config.define_app 'Example', ['example.com', 'localhost:3000', 'lvh.me:3000']
end
```
_config/initializers/pwa.rb_

```js
import ProgressiveWebApp from 'pwa-rails';
document.addEventListener( 'turbolinks:load', () => {
    const progressiveWebApp = new ProgressiveWebApp();
})
```
In a JS file you include on every page of your application.

**Comment by kirantpatil** [comment]
One more thing I forgot to tell you is, I installed onsenui as below.

> $ yarn add onsenui

**Comment by jonhue** [comment]
You need to provide the images you reference in your manifest. Put them in the `/public` folder.

**Comment by kirantpatil** [comment]
That issue is resolved now.
Now still the app is not recognized as PWA by my andorid browser. What else am I missing ?
For PWA is it compulsory to enable https ?

**Comment by jonhue** [comment]
You need to test if your app fulfills all criteria using Skylight in Chrome.
