### ISSUE TITLE
Clarify how to enable NPM

### ISSUE THREAD

**Issue by khelal** [jonhue/pwa#3]
Hi, can you please clarify the README on how to enable the JS side of things?

Specifically, I've added the js package using

````yarn add pwa-rails````

How do you then "enable" it?

**Comment by jonhue** [comment]
As mentioned in the install section if the README:

```js
import ProgressiveWebApp from 'pwa-rails';
document.addEventListener( 'turbolinks:load', () => {
    const progressiveWebApp = new ProgressiveWebApp();
})
```

**Note:** If you are already using a service that provides service workers (like OneSignal), import the `pwa` service worker:

```js
importScripts('https://example.com/pwa-sw.js');
```
